name: Build 3DS Calculator

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Project
        run: |
          make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Apple-Calculator-3DS
          path: |
            *.3dsx
            *.elf
